#!/usr/bin/env python3
"""
nc_imaging_only.py
------------------
Generates a standalone NC file that positions the camera over selected wells
of a 48-well plate. No printing.

Coordinates are G54, taken from the R-GEN 100 anchors that are confirmed to
work unchanged on the R-GEN 200.

Camera is physically at slot 5; T1 is selected to match the coordinate frame
the anchors were recorded in.

Usage:
  python nc_imaging_only.py A1 B3 C4        # specific wells
  python nc_imaging_only.py row1            # full row A (A1-A8)
  python nc_imaging_only.py col1            # full column 1 (A1-F1)
  python nc_imaging_only.py col1 col2 col3  # multiple columns
  python nc_imaging_only.py all_cols        # all 8 columns, column-major
  python nc_imaging_only.py all_rows        # all 6 rows, row-major
  python nc_imaging_only.py all             # all 48 wells, row-major

  python nc_imaging_only.py all_cols -o my_output.nc   # custom filename
"""

import sys
import re

# -----------------------------------------------------------------------------
# WELL COORDINATE MAP (G54)
# Corner anchors recorded with slot 1 selected, camera physically at slot 5.
# -----------------------------------------------------------------------------

ROWS = ['A', 'B', 'C', 'D', 'E', 'F']
COLS = [1, 2, 3, 4, 5, 6, 7, 8]

X_A1, Y_A1 = -250.160,  53.250
X_A8, Y_A8 = -158.200,  53.250
X_F1, Y_F1 = -250.160, -11.790
X_F8, Y_F8 = -158.200, -11.790

X_STEP = (X_A8 - X_A1) / 7   # per column
Y_STEP = (Y_F1 - Y_A1) / 5   # per row

Z_IMAGING = 20.00
Z_SAFE    = 40.00

N_ROWS = len(ROWS)
N_COLS = len(COLS)


def build_well_map():
    """Build dict of well_name -> (X, Y, Z) for all 48 wells."""
    wells = {}
    for r_idx, row in enumerate(ROWS):
        for c_idx, col in enumerate(COLS):
            x = round(X_A1 + c_idx * X_STEP, 3)
            y = round(Y_A1 + r_idx * Y_STEP, 3)
            wells[f"{row}{col}"] = (x, y, Z_IMAGING)
    return wells


WELL_MAP = build_well_map()


def parse_targets(args):
    """
    Parse input arguments into an ordered list of well names, no duplicates.
      - Well addresses : A1, B3, F8       (case-insensitive)
      - Row selectors  : row1 .. row6     (row1=A, ..., row6=F)
      - Col selectors  : col1 .. col8     (iterates A->F within that column)
      - 'all_cols'     : col1 then col2 ... col8  (column-major order)
      - 'all_rows'     : row1 then row2 ... row6  (row-major order)
      - 'all'          : all 48 wells in row-major order
    """
    selected = []
    seen = set()

    def add(well):
        w = well.upper()
        if w in WELL_MAP and w not in seen:
            selected.append(w)
            seen.add(w)

    def add_col(col_num):
        for r in ROWS:
            add(f"{r}{col_num}")

    def add_row(row_idx):
        row_letter = ROWS[row_idx]
        for c in COLS:
            add(f"{row_letter}{c}")

    for arg in args:
        arg_lower = arg.lower().strip()

        if arg_lower == 'all_cols':
            for c in COLS:
                add_col(c)

        elif arg_lower == 'all_rows':
            for r_idx in range(N_ROWS):
                add_row(r_idx)

        elif arg_lower == 'all':
            for r_idx in range(N_ROWS):
                add_row(r_idx)

        elif re.match(r'^row[1-6]$', arg_lower):
            add_row(int(arg_lower[3]) - 1)

        elif re.match(r'^col[1-8]$', arg_lower):
            add_col(int(arg_lower[3]))

        elif re.match(r'^[a-fA-F][1-8]$', arg):
            add(arg)

        else:
            print(f"  [WARNING] Unrecognised argument '{arg}' -- skipped.")
            print(f"            Valid: A1-F8, row1-row6, col1-col8, all_cols, all_rows, all")

    return selected


def generate_nc(well_names, output_name):
    """Generate the complete standalone imaging NC file."""
    lines = []
    lines.append(f"% {output_name}")
    lines.append("; Generated by nc_imaging_only.py")
    lines.append("; Camera imaging only -- no printing.")
    lines.append(f"; Wells: {', '.join(well_names)}")
    lines.append("; Slot 1 selected (T1) -- camera physically at slot 5.")
    lines.append(f"; Z safe = {Z_SAFE} mm  |  Z imaging = {Z_IMAGING} mm")
    lines.append(";")
    lines.append("; REGENHU")
    lines.append("; http://www.regenhu.com/")
    lines.append("; Translator 1.0.0.0")
    lines.append("")
    lines.append("; INITIALIZATION")
    lines.append("T1")
    lines.append("T0")
    lines.append("G803 ; Move to safe height")
    lines.append("; INITIALIZATION")
    lines.append("")
    lines.append("M110=0 ; Set printing progress to 0%")
    lines.append("T1")
    lines.append("G801 ; Measure tool")
    lines.append("")
    lines.append("#CONTOUR MODE ON [DEV PATH_DEV=0.08]")
    lines.append("")
    lines.append("M312 ; Wait for work zone temperature")
    lines.append("")
    lines.append("#FLUSH WAIT")
    lines.append("#CONTOUR MODE OFF          ; Exit tracking mode")
    lines.append("#FLUSH WAIT")
    lines.append("")
    lines.append("T1                         ; Select slot 1")
    lines.append("G803                       ; Move to system safe height")
    lines.append("")

    for well in well_names:
        x, y, z = WELL_MAP[well]
        lines.append(f"; --- Well {well} ---")
        lines.append(f"G00 G54 G90 Z{Z_SAFE:.3f}          ; Raise to safe Z first")
        lines.append(f"G00 X{x:.3f} Y{y:.3f}              ; Move XY to {well}")
        lines.append(f"G00 Z{z:.3f}                ; Lower to imaging height")
        lines.append(f'V.E.UserInteraction.Message = "Camera at {well} - trigger imaging, then click OK"')
        lines.append("M121                       ; Pause for manual camera trigger")
        lines.append("")

    lines.append("; --- Return home ---")
    lines.append(f"G00 G54 G90 Z{Z_SAFE:.3f}          ; Safe Z before going home")
    lines.append("G800                       ; Go home")
    lines.append("M110=1000")
    lines.append("M30")

    return "\r\n".join(lines) + "\r\n"


def main():
    args = [a for a in sys.argv[1:]]

    if not args:
        print(__doc__)
        sys.exit(1)

    # Optional -o output filename
    output_file = None
    if '-o' in args:
        i = args.index('-o')
        if i + 1 >= len(args):
            print("[ERROR] -o requires a filename.")
            sys.exit(1)
        output_file = args[i + 1]
        args = args[:i] + args[i + 2:]

    well_names = parse_targets(args)

    if not well_names:
        print("[ERROR] No valid wells selected.")
        print("  Valid wells    : A1-F8")
        print("  Row selectors  : row1 (=A) .. row6 (=F)")
        print("  Col selectors  : col1 .. col8")
        print("  Shortcuts      : all_cols, all_rows, all")
        sys.exit(1)

    if output_file is None:
        output_file = f"imaging_{len(well_names)}wells.nc"

    content = generate_nc(well_names, output_file)

    with open(output_file, 'w', newline='') as f:
        f.write(content)

    print(f"\n  Wells to image: {', '.join(well_names)}")
    print(f"  Output file   : {output_file}")
    print(f"  Done. {len(well_names)} well(s).\n")


if __name__ == "__main__":
    main()
