"""
unetplusplus_aggregate.py
--------------------------
Aggregate per-image evaluation metrics from test_info.csv into:
    1. Per-sample summary  (mean ± std across 6 replicates per sample)
    2. Dataset-level summary (median, IQR, mean ± std across samples)

Why this aggregation structure:
    - Each sample = one parameter combination (Pressure, Speed, Z-offset)
    - Each sample has 6 replicate images of the same print settings
    - Replicate-level mean ± std captures within-sample consistency
    - Sample-level median ± IQR is robust to outlier samples (failed prints)
      which is important with only ~7 test samples

Input
-----
    test_info.csv generated by unetplusplus_evaluate.py
    (must have iou_pred_annot, iou_pred_target, dice_pred_annot, pixel_acc filled)

Usage
-----
    python unetplusplus_aggregate.py
        --pred_dir  /home/hmo/.../dev_annot_test_unetpp_pred
        [--metrics  iou_pred_annot iou_pred_target dice_pred_annot pixel_acc]

Output
------
    <pred_dir>/
        sample_summary.csv      per-sample mean ± std across replicates
        dataset_summary.txt     dataset-level statistics (median, IQR, mean±std)
        aggregation_plot.png    box plots per metric across samples
"""

import argparse
import csv
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from pathlib import Path
from collections import defaultdict


DEFAULT_METRICS = [
    'iou_pred_annot',
    'iou_pred_target',
    'dice_pred_annot',
    'pixel_acc',
]

METRIC_LABELS = {
    'iou_pred_annot':  'IoU (pred vs annot)',
    'iou_pred_target': 'IoU (pred vs target)',
    'dice_pred_annot': 'Dice (pred vs annot)',
    'pixel_acc':       'Pixel accuracy',
}


def load_csv(csv_path):
    with open(csv_path, newline='') as f:
        reader = csv.DictReader(f, delimiter=';')
        return list(reader), reader.fieldnames


def aggregate(pred_dir, metrics):

    pred_dir = Path(pred_dir)
    csv_path = pred_dir / 'test_info.csv'

    if not csv_path.exists():
        print(f'[ERROR] test_info.csv not found in {pred_dir}')
        print('        Run unetplusplus_evaluate.py first.')
        return

    rows, fieldnames = load_csv(csv_path)

    # check metrics are present and filled
    available = []
    for m in metrics:
        filled = [r for r in rows if r.get(m, '').strip()]
        if not filled:
            print(f'  [SKIP] metric "{m}" is empty in CSV — '
                  f'run unetplusplus_evaluate.py first')
        else:
            available.append(m)

    if not available:
        print('[ERROR] No filled metric columns found. '
              'Run unetplusplus_evaluate.py first.')
        return

    print(f'Metrics to aggregate: {available}')
    print(f'Total images in CSV : {len(rows)}\n')

    # ── group by Sample_ID ───────────────────────────────────────────────────
    # sample_data[sid][metric] = [val_replicate_0, val_replicate_1, ...]
    sample_data = defaultdict(lambda: defaultdict(list))

    for row in rows:
        sid = row.get('Sample_ID', '').strip()
        if not sid:
            continue
        for m in available:
            val_str = row.get(m, '').strip()
            if val_str:
                try:
                    sample_data[sid][m].append(float(val_str))
                except ValueError:
                    pass

    sample_ids = sorted(sample_data.keys(), key=lambda x: int(x)
                        if x.isdigit() else x)

    print(f'Unique samples found: {len(sample_ids)} → {sample_ids}')
    print()

    # ── step 1: per-sample summary ───────────────────────────────────────────
    # For each sample: mean ± std across its replicates
    sample_rows = []
    for sid in sample_ids:
        row_out = {'Sample_ID': sid}
        n_rep   = 0
        for m in available:
            vals = sample_data[sid][m]
            if vals:
                n_rep = max(n_rep, len(vals))
                row_out[f'{m}_mean'] = f'{np.mean(vals):.4f}'
                row_out[f'{m}_std']  = f'{np.std(vals):.4f}'
                row_out[f'{m}_n']    = len(vals)
            else:
                row_out[f'{m}_mean'] = ''
                row_out[f'{m}_std']  = ''
                row_out[f'{m}_n']    = 0
        row_out['n_replicates'] = n_rep
        sample_rows.append(row_out)

    # write sample_summary.csv
    sample_csv_path = pred_dir / 'sample_summary.csv'
    sample_fieldnames = ['Sample_ID', 'n_replicates'] + [
        f for m in available for f in [f'{m}_mean', f'{m}_std', f'{m}_n']
    ]
    with open(sample_csv_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=sample_fieldnames,
                                delimiter=';', extrasaction='ignore')
        writer.writeheader()
        writer.writerows(sample_rows)

    print(f'── Per-sample summary (mean ± std across replicates) ──')
    header = f'{"Sample":>8}  ' + '  '.join(
        f'{METRIC_LABELS.get(m, m):>26}' for m in available)
    print(header)
    print('─' * len(header))
    for r in sample_rows:
        vals_str = '  '.join(
            f'{r.get(f"{m}_mean","n/a"):>12} ± {r.get(f"{m}_std","n/a"):<12}'
            for m in available
        )
        print(f'{r["Sample_ID"]:>8}  {vals_str}')
    print()

    # ── step 2: dataset-level summary ────────────────────────────────────────
    # Use per-sample MEANS as the unit of analysis
    # → each sample contributes one value (its replicate mean)
    # Report: median, IQR, mean ± std across samples

    dataset_lines = [
        f'Dataset-level evaluation',
        f'========================',
        f'n_samples        : {len(sample_ids)}',
        f'sample_ids       : {sample_ids}',
        f'aggregation      : per-sample mean (across replicates) → '
        f'then median/IQR/mean±std across samples',
        f'',
    ]

    print('── Dataset-level summary ──────────────────────────────')
    print(f'{"Metric":<30} {"Mean±Std":>20}  {"Median [IQR]":>24}  '
          f'{"Min":>8}  {"Max":>8}')
    print('─' * 96)

    for m in available:
        # collect per-sample means
        sample_means = []
        for sid in sample_ids:
            vals = sample_data[sid][m]
            if vals:
                sample_means.append(np.mean(vals))

        if not sample_means:
            continue

        arr    = np.array(sample_means)
        mean_  = np.mean(arr)
        std_   = np.std(arr)
        median_= np.median(arr)
        q1     = np.percentile(arr, 25)
        q3     = np.percentile(arr, 75)
        iqr_   = q3 - q1
        min_   = np.min(arr)
        max_   = np.max(arr)

        label  = METRIC_LABELS.get(m, m)
        mean_std_str  = f'{mean_:.4f} ± {std_:.4f}'
        median_iqr_str= f'{median_:.4f} [{q1:.4f}–{q3:.4f}]'

        print(f'{label:<30} {mean_std_str:>20}  {median_iqr_str:>24}  '
              f'{min_:>8.4f}  {max_:>8.4f}')

        dataset_lines += [
            f'Metric: {label}',
            f'  n_samples    : {len(sample_means)}',
            f'  mean ± std   : {mean_:.4f} ± {std_:.4f}',
            f'  median [IQR] : {median_:.4f} [{q1:.4f} – {q3:.4f}]',
            f'  min / max    : {min_:.4f} / {max_:.4f}',
            f'  per-sample   : {[round(v,4) for v in arr.tolist()]}',
            f'',
        ]

    print()

    # write dataset_summary.txt
    summary_path = pred_dir / 'dataset_summary.txt'
    summary_path.write_text('\n'.join(dataset_lines))

    print(f'✓ Per-sample CSV   → {sample_csv_path}')
    print(f'✓ Dataset summary  → {summary_path}')

    # ── step 3: box plot ─────────────────────────────────────────────────────
    n_metrics = len(available)
    fig, axes = plt.subplots(1, n_metrics,
                             figsize=(5 * n_metrics, 5),
                             squeeze=False)

    for j, m in enumerate(available):
        ax = axes[0][j]

        # per-sample means for box plot
        sample_means = [np.mean(sample_data[sid][m])
                        for sid in sample_ids
                        if sample_data[sid][m]]

        # individual replicate values (scatter)
        all_vals = [v for sid in sample_ids
                    for v in sample_data[sid][m]]

        # box plot of per-sample means
        bp = ax.boxplot(sample_means, patch_artist=True, widths=0.4,
                        boxprops=dict(facecolor='steelblue', alpha=0.5),
                        medianprops=dict(color='navy', linewidth=2),
                        whiskerprops=dict(color='steelblue'),
                        capprops=dict(color='steelblue'),
                        flierprops=dict(marker='o', color='tomato',
                                        markersize=6, alpha=0.7))

        # jitter scatter of individual replicate values
        jitter = np.random.default_rng(42).uniform(-0.08, 0.08,
                                                    size=len(all_vals))
        ax.scatter(np.ones(len(all_vals)) + jitter, all_vals,
                   color='steelblue', alpha=0.4, s=18, zorder=3,
                   label='replicates')

        # annotate sample means as dots
        ax.scatter(np.ones(len(sample_means)),
                   sample_means,
                   color='navy', s=50, zorder=4,
                   marker='D', label='sample mean')

        ax.set_xlim(0.5, 1.5)
        ax.set_ylim(-0.02, 1.05)
        ax.set_ylabel(METRIC_LABELS.get(m, m), fontsize=11)
        ax.set_xticks([])
        ax.set_title(METRIC_LABELS.get(m, m), fontsize=11)
        ax.grid(True, alpha=0.3, axis='y')
        ax.legend(fontsize=8, loc='lower right')

        # annotate median
        med = np.median(sample_means)
        ax.axhline(med, color='navy', linestyle=':', alpha=0.6,
                   linewidth=1.2)
        ax.text(1.22, med + 0.01, f'median={med:.3f}',
                fontsize=8, color='navy', va='bottom')

    fig.suptitle(f'Test set evaluation  '
                 f'({len(sample_ids)} samples, {len(rows)} images)',
                 fontsize=13)
    fig.tight_layout()
    plot_path = pred_dir / 'aggregation_plot.png'
    fig.savefig(plot_path, dpi=150)
    plt.close(fig)
    print(f'✓ Aggregation plot → {plot_path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Aggregate per-image metrics to sample and dataset level.'
    )
    parser.add_argument('--pred_dir', required=True,
        help='Folder with test_info.csv from unetplusplus_evaluate.py')
    parser.add_argument('--metrics', nargs='+', default=DEFAULT_METRICS,
        help='Metric columns to aggregate (default: all four)')
    args = parser.parse_args()

    aggregate(args.pred_dir, args.metrics)
