"""
unetplusplus_evaluate.py
------------------------
Compute segmentation metrics on U-Net++ predictions and update test_info.csv.

Two IoU metrics per image:
    1. iou_pred_annot    predicted mask vs annotation mask
    2. iou_pred_target   predicted mask vs target geometry extracted from
                         *-target-overlay.png (green + yellow pixels)

Target geometry source
----------------------
The target geometry is extracted directly from the existing
*-target-overlay.png files generated by draw_target_geometry.py.
Colour mapping in those overlays (alpha=0.5 blend with background):
    GREEN  region → target only (not in annotation)
    YELLOW region → target AND annotation overlap
    RED    region → annotation only (not in target)
    unchanged     → background

Target mask = GREEN + YELLOW pixels (anywhere the target geometry exists).

This approach is used because the real physical mm-scale of the target
geometry is currently unknown (microscope magnification unconfirmed).
Extracting from the overlay image uses the geometry exactly as rendered
by draw_target_geometry.py without requiring calibrated mm parameters.

Also computes:
    - Dice coefficient  (pred vs annot)
    - Pixel accuracy    (pred vs annot)
    - Recall of target  (what fraction of target pixels pred covers)

Input
-----
    <pred_dir>/               output folder from unetplusplus_test.py
        {stem}-pred-mask.png  predicted binary mask (0/1)
        {stem}-mask.png       annotation mask (copied by test script)
        {stem}-target-overlay.png  target overlay from draw_target_geometry.py

Usage
-----
    python unetplusplus_evaluate.py
        --pred_dir  /home/hmo/.../dev_annot_test_unetpp_pred

Output
------
    Updates test_info.csv in-place with all metric columns filled.
    Prints per-image and summary statistics.
"""

import argparse
import csv
import numpy as np
from pathlib import Path
from PIL import Image


# ── metrics ───────────────────────────────────────────────────────────────────
def binary_iou(pred, gt):
    p, g  = pred > 0, gt > 0
    inter = np.logical_and(p, g).sum()
    union = np.logical_or (p, g).sum()
    return float(inter) / float(union) if union > 0 else 0.0


def binary_dice(pred, gt):
    p, g  = pred > 0, gt > 0
    inter = np.logical_and(p, g).sum()
    denom = p.sum() + g.sum()
    return float(2 * inter) / float(denom) if denom > 0 else 0.0


def pixel_accuracy(pred, gt):
    p = (pred > 0).astype(np.uint8)
    g = (gt   > 0).astype(np.uint8)
    return float((p == g).sum()) / float(g.size)


def recall(pred, gt):
    """Fraction of gt pixels covered by pred."""
    p, g  = pred > 0, gt > 0
    inter = np.logical_and(p, g).sum()
    return float(inter) / float(g.sum()) if g.sum() > 0 else 0.0


# ── extract target mask from overlay image ────────────────────────────────────
def extract_target_from_overlay(overlay_path):
    """
    Extract target geometry mask from a *-target-overlay.png file.

    draw_target_geometry.py renders with alpha=0.5:
        GREEN  [60,220,60]  → target only  (blended with background)
        YELLOW [255,220,0]  → target AND pred overlap
        RED    [255,60,60]  → pred only
        unchanged           → background

    Target pixels = GREEN + YELLOW regions.

    Colour discrimination uses relative channel differences which are
    robust to the non-uniform iridescent background of the well plate.

    Returns binary mask (uint8, 1=target, 0=background), or None if
    overlay file not found.
    """
    if not Path(overlay_path).exists():
        return None

    img = np.array(Image.open(overlay_path).convert('RGB'))
    R   = img[:, :, 0].astype(int)
    G   = img[:, :, 1].astype(int)
    B   = img[:, :, 2].astype(int)

    # GREEN region: G strongly boosted, R and B not
    # expected blended value ≈ [88, 168, 88] for bg≈116
    green_only = (G - R > 50) & (G - B > 50)

    # YELLOW region: R and G both high, B low
    # expected blended value ≈ [185, 168, 58] for bg≈116
    yellow = (R > 140) & (G > 130) & (B < 100) & (np.abs(R - G) < 60)

    # target = anywhere target geometry exists
    target_mask = (green_only | yellow).astype(np.uint8)
    return target_mask


# ── main evaluation ───────────────────────────────────────────────────────────
def evaluate(pred_dir):

    pred_dir = Path(pred_dir)
    csv_path = pred_dir / 'test_info.csv'

    if not csv_path.exists():
        print(f'[ERROR] test_info.csv not found in {pred_dir}')
        print('        Run unetplusplus_test.py first.')
        return

    with open(csv_path, newline='') as f:
        reader     = csv.DictReader(f, delimiter=';')
        fieldnames = list(reader.fieldnames)
        rows       = list(reader)

    # ensure all metric columns exist
    new_cols = ['iou_pred_annot', 'iou_pred_target',
                'dice_pred_annot', 'pixel_acc', 'recall_target']
    for col in new_cols:
        if col not in fieldnames:
            fieldnames.append(col)

    # diagnostic
    existing_preds = sorted(p.name for p in pred_dir.glob('*-pred-mask.png'))
    print(f'Found {len(existing_preds)} pred masks in {pred_dir}')
    csv_stems = [r.get('stem', '') for r in rows]
    print(f'CSV has {len(rows)} rows')
    if existing_preds:
        print(f'  Example pred file : {existing_preds[0]}')
    if csv_stems:
        print(f'  Example CSV stem  : {csv_stems[0]}')
        print(f'  Expected pred path: '
              f'{pred_dir / (csv_stems[0] + "-pred-mask.png")}')
    print()

    results_annot  = []
    results_target = []

    for row in rows:
        stem = row['stem']
        print(f'  {stem}')

        # ── load predicted mask ───────────────────────────────────────────────
        pred_path = pred_dir / f'{stem}-pred-mask.png'
        if not pred_path.exists():
            print(f'    [SKIP] pred mask not found: {pred_path.name}')
            continue

        pred_arr = np.array(Image.open(pred_path))
        if pred_arr.ndim == 3:
            pred_arr = pred_arr[:, :, 0]
        pred_bin = (pred_arr > 0).astype(np.uint8)

        # ── metric 1: pred vs annotation ─────────────────────────────────────
        annot_path = pred_dir / f'{stem}-mask.png'
        if annot_path.exists():
            annot_arr = np.array(Image.open(annot_path))
            if annot_arr.ndim == 3:
                annot_arr = annot_arr[:, :, 0]
            annot_bin = (annot_arr > 0).astype(np.uint8)

            iou_pa  = binary_iou(pred_bin,  annot_bin)
            dice_pa = binary_dice(pred_bin, annot_bin)
            acc_pa  = pixel_accuracy(pred_bin, annot_bin)

            row['iou_pred_annot']  = f'{iou_pa:.4f}'
            row['dice_pred_annot'] = f'{dice_pa:.4f}'
            row['pixel_acc']       = f'{acc_pa:.4f}'
            results_annot.append(iou_pa)
            print(f'    IoU(pred|annot)={iou_pa:.3f}  '
                  f'Dice={dice_pa:.3f}  Acc={acc_pa:.3f}')
        else:
            row['iou_pred_annot']  = ''
            row['dice_pred_annot'] = ''
            row['pixel_acc']       = ''
            print(f'    [no annotation mask]')

        # ── metric 2: pred vs target (from overlay image) ─────────────────────
        overlay_path = pred_dir / f'{stem}-target-overlay.png'
        target_mask  = extract_target_from_overlay(overlay_path)

        if target_mask is None:
            row['iou_pred_target'] = ''
            row['recall_target']   = ''
            print(f'    [no target-overlay.png] skipping target metric')
            continue

        # resize pred_bin to target_mask size if needed (should be same)
        if pred_bin.shape != target_mask.shape:
            from PIL import Image as PILImage
            import cv2
            pred_bin = cv2.resize(
                pred_bin,
                (target_mask.shape[1], target_mask.shape[0]),
                interpolation=cv2.INTER_NEAREST
            )

        iou_pt     = binary_iou(pred_bin, target_mask)
        recall_pt  = recall(pred_bin, target_mask)

        row['iou_pred_target'] = f'{iou_pt:.4f}'
        row['recall_target']   = f'{recall_pt:.4f}'
        results_target.append(iou_pt)
        print(f'    IoU(pred|target)={iou_pt:.3f}  '
              f'Recall(target)={recall_pt:.3f}  '
              f'[target_px={target_mask.sum()}]')

    # ── write updated CSV ─────────────────────────────────────────────────────
    with open(csv_path, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames,
                                delimiter=';', extrasaction='ignore')
        writer.writeheader()
        writer.writerows(rows)

    # ── summary ───────────────────────────────────────────────────────────────
    print('\n── Summary ──────────────────────────────────────────────')
    if results_annot:
        print(f'  IoU  (pred|annot) :  '
              f'{np.mean(results_annot):.3f} ± {np.std(results_annot):.3f}  '
              f'[{np.min(results_annot):.3f} – {np.max(results_annot):.3f}]')
    if results_target:
        print(f'  IoU  (pred|target):  '
              f'{np.mean(results_target):.3f} ± {np.std(results_target):.3f}  '
              f'[{np.min(results_target):.3f} – {np.max(results_target):.3f}]')
    print(f'\n✓ Updated metrics → {csv_path}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Evaluate U-Net++ predictions. '
                    'Target geometry extracted from *-target-overlay.png files.'
    )
    parser.add_argument('--pred_dir', required=True,
        help='Folder with unetplusplus_test.py outputs and '
             '*-target-overlay.png files')
    args = parser.parse_args()

    evaluate(pred_dir=args.pred_dir)