% data_collection_48well_8cols_s0-s28.nc
; Generated by generate_nc_files.py
; Geometry: 2D cross-hatch grid | 3+3 strands | 2x2 open pores | single layer
; CSV: lhs_bioprint_samples_semicolon.csv
; Temperature: set manually in Architect UI (not in G-code)
;
; Col   SampleID   P(kPa)     F(mm/s)    Z(mm)   
; 1     0          50         9.0        0.3     
; 2     4          60         14.0       0.2     
; 3     8          70         13.0       0.2     
; 4     12         80         9.0        0.2     
; 5     16         90         10.0       0.2     
; 6     20         100        14.0       0.1     
; 7     24         110        8.0        0.5     
; 8     28         120        13.0       0.4     
;
; REGENHU
; http://www.regenhu.com/
; Translator 1.0.0.0
; Date 2026-04-13
; ESTIMATED_PRINTING_TIME 0:03:19.061356

; INITIALIZATION
T1
M200=500 ; Set pressure to 50kPa
T0
G803 ; Move to safe height
; INITIALIZATION

M110=0 ; Set printing progress to 0%
T1
G801 ; Measure tool

#CONTOUR MODE ON [DEV PATH_DEV=0.08]

M312 ; Wait for work zone temperature

; -- Col 1 | Sample 0 | P=50kPa  F=9.0mm/s  Z=0.300mm --
G805[-45.785, 32.720, 2.620] ; G55 origin: A1
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=500 ; pressure 50kPa
F9.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.300
M110=40
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A1
G805[-45.785, 19.640, 2.620] ; G55 origin: B1
G55
G00 Z18.400
M200=500
F9.000
X-2.000 Y-2.500
Z0.300
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B1
G805[-45.785, 6.560, 2.620] ; G55 origin: C1
G55
G00 Z18.400
M200=500
F9.000
X-2.000 Y-2.500
Z0.300
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C1
G805[-45.785, -6.520, 2.620] ; G55 origin: D1
G55
G00 Z18.400
M200=500
F9.000
X-2.000 Y-2.500
Z0.300
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D1
G805[-45.785, -19.600, 2.620] ; G55 origin: E1
G55
G00 Z18.400
M200=500
F9.000
X-2.000 Y-2.500
Z0.300
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E1
G805[-45.785, -32.680, 2.620] ; G55 origin: F1
G55
G00 Z18.400
M200=500
F9.000
X-2.000 Y-2.500
Z0.300
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.300                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.300                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F1

; -- Col 2 | Sample 4 | P=60kPa  F=14.0mm/s  Z=0.200mm --
G805[-32.705, 32.720, 2.620] ; G55 origin: A2
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=600 ; pressure 60kPa
F14.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A2
G805[-32.705, 19.640, 2.620] ; G55 origin: B2
G55
G00 Z18.400
M200=600
F14.000
X-2.000 Y-2.500
Z0.200
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B2
G805[-32.705, 6.560, 2.620] ; G55 origin: C2
G55
G00 Z18.400
M200=600
F14.000
X-2.000 Y-2.500
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C2
G805[-32.705, -6.520, 2.620] ; G55 origin: D2
G55
G00 Z18.400
M200=600
F14.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D2
G805[-32.705, -19.600, 2.620] ; G55 origin: E2
G55
G00 Z18.400
M200=600
F14.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E2
G805[-32.705, -32.680, 2.620] ; G55 origin: F2
G55
G00 Z18.400
M200=600
F14.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F2

; -- Col 3 | Sample 8 | P=70kPa  F=13.0mm/s  Z=0.200mm --
G805[-19.625, 32.720, 2.620] ; G55 origin: A3
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=700 ; pressure 70kPa
F13.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A3
G805[-19.625, 19.640, 2.620] ; G55 origin: B3
G55
G00 Z18.400
M200=700
F13.000
X-2.000 Y-2.500
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B3
G805[-19.625, 6.560, 2.620] ; G55 origin: C3
G55
G00 Z18.400
M200=700
F13.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C3
G805[-19.625, -6.520, 2.620] ; G55 origin: D3
G55
G00 Z18.400
M200=700
F13.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D3
G805[-19.625, -19.600, 2.620] ; G55 origin: E3
G55
G00 Z18.400
M200=700
F13.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E3
G805[-19.625, -32.680, 2.620] ; G55 origin: F3
G55
G00 Z18.400
M200=700
F13.000
X-2.000 Y-2.500
Z0.200
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F3

; -- Col 4 | Sample 12 | P=80kPa  F=9.0mm/s  Z=0.200mm --
G805[-6.545, 32.720, 2.620] ; G55 origin: A4
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=800 ; pressure 80kPa
F9.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A4
G805[-6.545, 19.640, 2.620] ; G55 origin: B4
G55
G00 Z18.400
M200=800
F9.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B4
G805[-6.545, 6.560, 2.620] ; G55 origin: C4
G55
G00 Z18.400
M200=800
F9.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C4
G805[-6.545, -6.520, 2.620] ; G55 origin: D4
G55
G00 Z18.400
M200=800
F9.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D4
G805[-6.545, -19.600, 2.620] ; G55 origin: E4
G55
G00 Z18.400
M200=800
F9.000
X-2.000 Y-2.500
Z0.200
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E4
G805[-6.545, -32.680, 2.620] ; G55 origin: F4
G55
G00 Z18.400
M200=800
F9.000
X-2.000 Y-2.500
Z0.200
M110=120
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F4

; -- Col 5 | Sample 16 | P=90kPa  F=10.0mm/s  Z=0.200mm --
G805[6.535, 32.720, 2.620] ; G55 origin: A5
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=900 ; pressure 90kPa
F10.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A5
G805[6.535, 19.640, 2.620] ; G55 origin: B5
G55
G00 Z18.400
M200=900
F10.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B5
G805[6.535, 6.560, 2.620] ; G55 origin: C5
G55
G00 Z18.400
M200=900
F10.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C5
G805[6.535, -6.520, 2.620] ; G55 origin: D5
G55
G00 Z18.400
M200=900
F10.000
X-2.000 Y-2.500
Z0.200
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D5
G805[6.535, -19.600, 2.620] ; G55 origin: E5
G55
G00 Z18.400
M200=900
F10.000
X-2.000 Y-2.500
Z0.200
M110=120
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E5
G805[6.535, -32.680, 2.620] ; G55 origin: F5
G55
G00 Z18.400
M200=900
F10.000
X-2.000 Y-2.500
Z0.200
M110=130
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F5

; -- Col 6 | Sample 20 | P=100kPa  F=14.0mm/s  Z=0.100mm --
G805[19.615, 32.720, 2.620] ; G55 origin: A6
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1000 ; pressure 100kPa
F14.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.100
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A6
G805[19.615, 19.640, 2.620] ; G55 origin: B6
G55
G00 Z18.400
M200=1000
F14.000
X-2.000 Y-2.500
Z0.100
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B6
G805[19.615, 6.560, 2.620] ; G55 origin: C6
G55
G00 Z18.400
M200=1000
F14.000
X-2.000 Y-2.500
Z0.100
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C6
G805[19.615, -6.520, 2.620] ; G55 origin: D6
G55
G00 Z18.400
M200=1000
F14.000
X-2.000 Y-2.500
Z0.100
M110=120
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D6
G805[19.615, -19.600, 2.620] ; G55 origin: E6
G55
G00 Z18.400
M200=1000
F14.000
X-2.000 Y-2.500
Z0.100
M110=130
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E6
G805[19.615, -32.680, 2.620] ; G55 origin: F6
G55
G00 Z18.400
M200=1000
F14.000
X-2.000 Y-2.500
Z0.100
M110=140
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.100                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.100                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F6

; -- Col 7 | Sample 24 | P=110kPa  F=8.0mm/s  Z=0.500mm --
G805[32.695, 32.720, 2.620] ; G55 origin: A7
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1100 ; pressure 110kPa
F8.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.500
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A7
G805[32.695, 19.640, 2.620] ; G55 origin: B7
G55
G00 Z18.400
M200=1100
F8.000
X-2.000 Y-2.500
Z0.500
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B7
G805[32.695, 6.560, 2.620] ; G55 origin: C7
G55
G00 Z18.400
M200=1100
F8.000
X-2.000 Y-2.500
Z0.500
M110=120
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C7
G805[32.695, -6.520, 2.620] ; G55 origin: D7
G55
G00 Z18.400
M200=1100
F8.000
X-2.000 Y-2.500
Z0.500
M110=130
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D7
G805[32.695, -19.600, 2.620] ; G55 origin: E7
G55
G00 Z18.400
M200=1100
F8.000
X-2.000 Y-2.500
Z0.500
M110=140
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E7
G805[32.695, -32.680, 2.620] ; G55 origin: F7
G55
G00 Z18.400
M200=1100
F8.000
X-2.000 Y-2.500
Z0.500
M110=150
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.500                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.500                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F7

; -- Col 8 | Sample 28 | P=120kPa  F=13.0mm/s  Z=0.400mm --
G805[45.775, 32.720, 2.620] ; G55 origin: A8
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1200 ; pressure 120kPa
F13.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.400
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A8
G805[45.775, 19.640, 2.620] ; G55 origin: B8
G55
G00 Z18.400
M200=1200
F13.000
X-2.000 Y-2.500
Z0.400
M110=120
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B8
G805[45.775, 6.560, 2.620] ; G55 origin: C8
G55
G00 Z18.400
M200=1200
F13.000
X-2.000 Y-2.500
Z0.400
M110=130
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C8
G805[45.775, -6.520, 2.620] ; G55 origin: D8
G55
G00 Z18.400
M200=1200
F13.000
X-2.000 Y-2.500
Z0.400
M110=140
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D8
G805[45.775, -19.600, 2.620] ; G55 origin: E8
G55
G00 Z18.400
M200=1200
F13.000
X-2.000 Y-2.500
Z0.400
M110=150
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E8
G805[45.775, -32.680, 2.620] ; G55 origin: F8
G55
G00 Z18.400
M200=1200
F13.000
X-2.000 Y-2.500
Z0.400
M110=160
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.400                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.400                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F8

#FLUSH WAIT

; ============================================================
; CAMERA IMAGING POSITIONS
; Wells: A1, B1, C1, D1, E1, F1, A2, B2, C2, D2, E2, F2, A3, B3, C3, D3, E3, F3, A4, B4, C4, D4, E4, F4, A5, B5, C5, D5, E5, F5, A6, B6, C6, D6, E6, F6, A7, B7, C7, D7, E7, F7, A8, B8, C8, D8, E8, F8
; Column-major order: col1 (A1-F1) -> col2 (A2-F2) -> ...
; Slot 1 selected (T1) -- camera physically at slot 5.
; Z safe = 40.0 mm  |  Z imaging = 20.0 mm
; ============================================================

#FLUSH WAIT
#CONTOUR MODE OFF          ; Exit tracking mode from printing
#FLUSH WAIT

T1                         ; Select slot 1
G803                       ; Move to system safe height

; --- Well A1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y53.250              ; Move XY to A1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y40.242              ; Move XY to B1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y27.234              ; Move XY to C1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y14.226              ; Move XY to D1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y1.218              ; Move XY to E1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y-11.790              ; Move XY to F1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y53.250              ; Move XY to A2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y40.242              ; Move XY to B2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y27.234              ; Move XY to C2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y14.226              ; Move XY to D2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y1.218              ; Move XY to E2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y-11.790              ; Move XY to F2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y53.250              ; Move XY to A3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y40.242              ; Move XY to B3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y27.234              ; Move XY to C3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y14.226              ; Move XY to D3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y1.218              ; Move XY to E3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y-11.790              ; Move XY to F3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y53.250              ; Move XY to A4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y40.242              ; Move XY to B4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y27.234              ; Move XY to C4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y14.226              ; Move XY to D4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y1.218              ; Move XY to E4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y-11.790              ; Move XY to F4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y53.250              ; Move XY to A5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y40.242              ; Move XY to B5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y27.234              ; Move XY to C5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y14.226              ; Move XY to D5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y1.218              ; Move XY to E5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F5 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-197.611 Y-11.790              ; Move XY to F5
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F5 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y53.250              ; Move XY to A6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y40.242              ; Move XY to B6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y27.234              ; Move XY to C6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y14.226              ; Move XY to D6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y1.218              ; Move XY to E6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F6 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-184.474 Y-11.790              ; Move XY to F6
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F6 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y53.250              ; Move XY to A7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y40.242              ; Move XY to B7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y27.234              ; Move XY to C7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y14.226              ; Move XY to D7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y1.218              ; Move XY to E7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F7 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-171.337 Y-11.790              ; Move XY to F7
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F7 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y53.250              ; Move XY to A8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y40.242              ; Move XY to B8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y27.234              ; Move XY to C8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y14.226              ; Move XY to D8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y1.218              ; Move XY to E8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F8 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-158.200 Y-11.790              ; Move XY to F8
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F8 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Return home ---
G00 G54 G90 Z40.000          ; Safe Z before going home
G800                       ; Go home
M110=1000
M30