% data_collection_48well_8cols_s0-s49.nc
; Generated by generate_nc_files.py
; Geometry: 2D cross-hatch grid | 3+3 strands | 2x2 open pores | single layer
; CSV: lhs_bioprint_samples_semicolon.csv
; Temperature: set manually in Architect UI (not in G-code)
;
; Pressure sweep: 30-140 kPa, step 5, 23 wells (A1-F1, A2-F2, A3-F3, A4-E4)
; Col   Wells      P(kPa)     F(mm/s)    Z(mm)   
; 1     A1-F1      30-55      10.0       0.2     
; 2     A2-F2      60-85      10.0       0.2     
; 3     A3-F3      90-115     10.0       0.2     
; 4     A4-E4      120-140    10.0       0.2     
;
; REGENHU
; http://www.regenhu.com/
; Translator 1.0.0.0
; Date 2026-04-13
; ESTIMATED_PRINTING_TIME 0:03:19.061356

; INITIALIZATION
T1
M200=300 ; Set pressure to 30kPa
T0
G803 ; Move to safe height
; INITIALIZATION

M110=0 ; Set printing progress to 0%
T1
G801 ; Measure tool

#CONTOUR MODE ON [DEV PATH_DEV=0.08]

M312 ; Wait for work zone temperature

; -- Col 1 | Sample 0 | P=10-20kPa  F=10.0mm/s  Z=0.200mm --
G805[-45.785, 32.720, 2.620] ; G55 origin: A1
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=300 ; pressure 30kPa
F10.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=40
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A1
G805[-45.785, 19.640, 2.620] ; G55 origin: B1
G55
G00 Z18.400
M200=350
F10.000
X-2.000 Y-2.500
Z0.200
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B1
G805[-45.785, 6.560, 2.620] ; G55 origin: C1
G55
G00 Z18.400
M200=400
F10.000
X-2.000 Y-2.500
Z0.200
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C1
G805[-45.785, -6.520, 2.620] ; G55 origin: D1
G55
G00 Z18.400
M200=450
F10.000
X-2.000 Y-2.500
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D1
G805[-45.785, -19.600, 2.620] ; G55 origin: E1
G55
G00 Z18.400
M200=500
F10.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E1
G805[-45.785, -32.680, 2.620] ; G55 origin: F1
G55
G00 Z18.400
M200=550
F10.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F1

; -- Col 2 | Sample 7 | P=55kPa  F=10.0mm/s  Z=0.200mm --
G805[-32.705, 32.720, 2.620] ; G55 origin: A2
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=600 ; pressure 60kPa
F10.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=50
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A2
G805[-32.705, 19.640, 2.620] ; G55 origin: B2
G55
G00 Z18.400
M200=650
F10.000
X-2.000 Y-2.500
Z0.200
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B2
G805[-32.705, 6.560, 2.620] ; G55 origin: C2
G55
G00 Z18.400
M200=700
F10.000
X-2.000 Y-2.500
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C2
G805[-32.705, -6.520, 2.620] ; G55 origin: D2
G55
G00 Z18.400
M200=750
F10.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D2
G805[-32.705, -19.600, 2.620] ; G55 origin: E2
G55
G00 Z18.400
M200=800
F10.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E2
G805[-32.705, -32.680, 2.620] ; G55 origin: F2
G55
G00 Z18.400
M200=850
F10.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F2

; -- Col 3 | Sample 14 | P=85kPa  F=10.0mm/s  Z=0.200mm --
G805[-19.625, 32.720, 2.620] ; G55 origin: A3
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=900 ; pressure 90kPa
F10.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=60
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A3
G805[-19.625, 19.640, 2.620] ; G55 origin: B3
G55
G00 Z18.400
M200=950
F10.000
X-2.000 Y-2.500
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B3
G805[-19.625, 6.560, 2.620] ; G55 origin: C3
G55
G00 Z18.400
M200=1000
F10.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C3
G805[-19.625, -6.520, 2.620] ; G55 origin: D3
G55
G00 Z18.400
M200=1050
F10.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D3
G805[-19.625, -19.600, 2.620] ; G55 origin: E3
G55
G00 Z18.400
M200=1100
F10.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E3
G805[-19.625, -32.680, 2.620] ; G55 origin: F3
G55
G00 Z18.400
M200=1150
F10.000
X-2.000 Y-2.500
Z0.200
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well F3

; -- Col 4 | Sample 21 | P=115kPa  F=10.0mm/s  Z=0.200mm --
G805[-6.545, 32.720, 2.620] ; G55 origin: A4
G55

; Changing tool to 'PSD 1'
#FLUSH WAIT
T1
G807[1, 0.002, 0.002] ; time-based start/stop delays [s]
M200=1200 ; pressure 120kPa
F10.000
G00 X-2.000 Y-2.500
M151 ; Engage tool for printing
Z0.200
M110=70
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well A4
G805[-6.545, 19.640, 2.620] ; G55 origin: B4
G55
G00 Z18.400
M200=1250
F10.000
X-2.000 Y-2.500
Z0.200
M110=80
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well B4
G805[-6.545, 6.560, 2.620] ; G55 origin: C4
G55
G00 Z18.400
M200=1300
F10.000
X-2.000 Y-2.500
Z0.200
M110=90
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well C4
G805[-6.545, -6.520, 2.620] ; G55 origin: D4
G55
G00 Z18.400
M200=1350
F10.000
X-2.000 Y-2.500
Z0.200
M110=100
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well D4
G805[-6.545, -19.600, 2.620] ; G55 origin: E4
G55
G00 Z18.400
M200=1400
F10.000
X-2.000 Y-2.500
Z0.200
M110=110
G807[2, 0.300, 0.300]
M160                      ; H1 ON
G01 X2.300      ; H-strand 1
M161                      ; H1 OFF
G00 X2.000 Y0.000  ; → H-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; H2 ON
G01 X-2.300      ; H-strand 2
M161                      ; H2 OFF
G00 X-2.000 Y2.500  ; → H-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; H3 ON
G01 X2.300      ; H-strand 3
M161                      ; H3 OFF
G00 X2.600          ; tail-eq 0.3mm — match H1/H2 residual
G00 Z1.200                   ; lift 1.0mm — clear H-strands
G00 X-2.500 Y-2.000  ; → V-strand 1 start
G00 Z0.200                    ; lower to print height
G807[2, 0.300, 0.300]
M160                      ; V1 ON
G01 Y2.300      ; V-strand 1
M161                      ; V1 OFF
G00 X0.000 Y2.000  ; → V-strand 2 start
G807[2, 0.300, 0.300]
M160                      ; V2 ON
G01 Y-2.300      ; V-strand 2
M161                      ; V2 OFF
G00 X2.500 Y-2.000  ; → V-strand 3 start
G807[2, 0.300, 0.300]
M160                      ; V3 ON
G01 Y2.300      ; V-strand 3
M161                      ; V3 OFF
G00 Y2.600          ; tail-eq 0.3mm — match V1/V2 residual
G00 Z18.400 ; lift after well E4
; CAMERA IMAGING POSITIONS
; Wells: A1, B1, C1, D1, E1, F1, A2, B2, C2, D2, E2, F2, A3, B3, C3, D3, E3, F3, A4, B4, C4, D4, E4, F4, A5, B5, C5, D5, E5, F5, A6, B6, C6, D6, E6, F6, A7, B7, C7, D7, E7, F7, A8, B8, C8, D8, E8, F8
; Column-major order: col1 (A1-F1) -> col2 (A2-F2) -> ...
; Slot 1 selected (T1) -- camera physically at slot 5.
; Z safe = 40.0 mm  |  Z imaging = 20.0 mm
; ============================================================

#FLUSH WAIT
#CONTOUR MODE OFF          ; Exit tracking mode from printing
#FLUSH WAIT

T1                         ; Select slot 1
G803                       ; Move to system safe height

; --- Well A1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y53.250              ; Move XY to A1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y40.242              ; Move XY to B1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y27.234              ; Move XY to C1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y14.226              ; Move XY to D1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y1.218              ; Move XY to E1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F1 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-250.160 Y-11.790              ; Move XY to F1
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F1 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y53.250              ; Move XY to A2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y40.242              ; Move XY to B2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y27.234              ; Move XY to C2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y14.226              ; Move XY to D2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y1.218              ; Move XY to E2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F2 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-237.023 Y-11.790              ; Move XY to F2
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F2 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y53.250              ; Move XY to A3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y40.242              ; Move XY to B3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y27.234              ; Move XY to C3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y14.226              ; Move XY to D3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y1.218              ; Move XY to E3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well F3 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-223.886 Y-11.790              ; Move XY to F3
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at F3 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well A4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y53.250              ; Move XY to A4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at A4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well B4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y40.242              ; Move XY to B4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at B4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well C4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y27.234              ; Move XY to C4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at C4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well D4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y14.226              ; Move XY to D4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at D4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Well E4 ---
G00 G54 G90 Z40.000          ; Raise to safe Z first
G00 X-210.749 Y1.218              ; Move XY to E4
G00 Z20.000                ; Lower to imaging height
V.E.UserInteraction.Message = "Camera at E4 - trigger imaging, then click OK"
M121                       ; Pause for manual camera trigger

; --- Return home ---
G00 G54 G90 Z40.000          ; Safe Z before going home
G800                       ; Go home
M110=1000
M30